### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 创建新用户
POST http://localhost:8081/api/users
Content-Type: application/json

{
  "name": "测试小能手",
  "age": 18,
  "password": "mysecretpassword123"
}